version: '3.1'

services:
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    volumes:
      - ./datadb/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer-mysql:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - mysql-db
